### ISSUE TITLE
Question about the requirement of GPU

### ISSUE THREAD

**Issue by Hugo-cell111** [lizhaoliu-Lec/CPCM#3]
Hi! I wonder how many GPUs and what kind of GPUs are required in general weakly-supervised semantic segmentation task including your work? Plus as introduced in your paper, 1 or 2 TITAN 3090 GPU is enough, so how long does it take for a single group of experiment? Thanks!

**Comment by lizhaoliu-Lec** [comment]
One 3090 for S3DIS
Two 3090s for ScanNetV2
Four 3090 for SemanticKITTI

**Comment by Hugo-cell111** [comment]
How long does it take for a single group of experiment for each dataset?

**Comment by Hugo-cell111** [comment]
Thanks!
