### ISSUE TITLE
question about multi-GPUs training

### ISSUE THREAD

**Issue by mooncakehub** [lizhaoliu-Lec/CPCM#5]
thank you for your excellent work. 
 because my sigle gpu's memory isn't enough, I want to know if your code can be modified use multi-gpus to train.

**Comment by lizhaoliu-Lec** [comment]
The code supports multi GPU training, controlled by the flag `CUDA_VISIBLE_DEVICES`.

For now, the default settings for S3DIS and ScanNet V2 are 2 point-clouds per-GPU.

To reduce the GPU memory consumption, just set `DATA.batch_size 1`. I hope the batch size of 1 can be supported by your GPU.

**Comment by mooncakehub** [comment]
thank  you for your reply. I have several 2080ti gpus ,but each of them has 12G memory.So I want to use two gpus to train S3DIS. 
Because `DATA.batch_size 1` may not perform well as your paper said.
 I haven't tried many gpus parallels, so I don't know if it's feasible
