### ISSUE TITLE
how to prepare weak labels of S3DIS dataset?

### ISSUE THREAD

**Issue by PointCloudYC** [lizhaoliu-Lec/CPCM#6]
Hi? Could you please share scripts for preparing weak labels of the S3DIS dataset?
Thanks.

**Comment by lizhaoliu-Lec** [comment]
See code in `prepare_dataset/stanford/preprocess_stanford.py` for details.

**Comment by lizhaoliu-Lec** [comment]
I just uploaded the code in `prepare_dataset/stanford/data_efficient_v2.py`.

For fair comparisons, I recommend using our generated point ids.

A quick note, we have tried generating different point ids w.r.t different label ratios and the results do not change too much.
