### ISSUE TITLE
Dose your code only can be train on MinkowskiEngine 0.4.3 Env now

### ISSUE THREAD

**Issue by mooncakehub** [lizhaoliu-Lec/CPCM#7]
thank you for your excellent work. my hardware are 2080ti *5,may be I can't use  MinkowskiEngine 0.5.4.
Dose your code only can be train on MinkowskiEngine 0.4.3 Env now,beause I see this:
![1701395510938](https://github.com/lizhaoliu-Lec/CPCM/assets/138660085/001b85a4-fae0-40cb-bdf9-ce858934a67e)

**Comment by lizhaoliu-Lec** [comment]
Yes, the code is compatible with ME 0.4.3. Follow the instructions you are looking at and feel free to ask any questions.

**Comment by lizhaoliu-Lec** [comment]
What's your pytorch and cuda version?

**Comment by mooncakehub** [comment]
pytorch1.10.1 and cudatoolkit 11.3 g++/gcc 7.5.0, I can't install g++/gcc9,because the other dependencies don't match

**Comment by lizhaoliu-Lec** [comment]
Follow the instructions in README and try again.
PyTorch 1.6
CUDA 10.2 
GCC/G++ 7.5.0

**Comment by mooncakehub** [comment]
Thank you.I install envirionment ME0.5.4 with GPU 3060 successfully.And I downloaded your processed S3DID dataset. how can I start training

**Comment by lizhaoliu-Lec** [comment]
Use one of the command in scripts/S3DIS.sh.
