### ISSUE TITLE
What type of data is percentage0.001evenc?

### ISSUE THREAD

**Issue by peter218** [lizhaoliu-Lec/CPCM#8]
I want to know the data type of percentage0.001evenc and how to open it，thank you

**Comment by lizhaoliu-Lec** [comment]
It's a torch tensor. You can load it by `sampled_inds = torch.load(PATH_TO_SAMPLED_INDS_FILE)`

**Comment by peter218** [comment]
OK thank you






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lizhaoliu-Lec/CPCM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月24日(星期天) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lizhaoliu-Lec/CPCM] What type of data is percentage0.001evenc? (Issue #8)





 
It's a torch tensor. You can load it by sampled_inds = torch.load(PATH_TO_SAMPLED_INDS_FILE)
