### ISSUE TITLE
can you provide 0.02% S3DIS experiment scripts？

### ISSUE THREAD

**Issue by momoyo126** [lizhaoliu-Lec/CPCM#9]

**Comment by lizhaoliu-Lec** [comment]
# FIXME mask mode grid, size 8, ratio 0.75
# FIXME unp weight 0.
# FIXME mask weight 5
CUDA_VISIBLE_DEVICES=4 python launch.py --master_port=27536 ddp_train.py --config config.exp/default-pazhou001.yaml \
      GENERAL.exp_name 2e-4_percentage_ts_notAlign_PSD_nogColorJitter_noUnp_jsV2_mask075GridSize8_extraMaskStreamSelfCorr_weight5_noThres \
    TRAINER.name TwoStreamTrainer \
    MODEL.out_channels 13 \
    DATA.name StanfordDataLoader \
    DATA.dataset StanfordArea5Dataset \
    DATA.voxel_size 0.05 \
    DATA.batch_size 2 \
    DATA.train_limit_numpoints 1000000 \
    OPTIMIZER.lr 0.01 \
    OPTIMIZER.weight_decay 0.001 \
    SCHEDULER.name PolyLR \
    TRAINER.epochs 180 \
    EVALUATOR.iou_num_class 13 \
    DATA.stanford3d_sampled_inds /home/liulizhao/datasets/stanford_fully_supervised_preprocessed/points/percentage0.0002evenc \
    DATA.sparse_label False \
    DATA.two_stream True \
    MODEL.two_stream_model_apply True \
    TRAINER.two_stream_feats_key semantic_scores \
    TRAINER.two_stream_loss_mode js_divergence_v2 \
    TRAINER.two_stream_seg_both True \
    TRAINER.two_stream_loss_weight 0.0 \
    AUGMENTATION.use_color_jitter False \
    TRAINER.two_stream_mask_ratio 0.75 \
    TRAINER.two_stream_mask_mode grid \
    TRAINER.two_stream_loss_mask_mode js_divergence_v2 \
    TRAINER.two_stream_mask_extra_stream True \
    TRAINER.two_stream_mask_feats_key semantic_scores \
    TRAINER.two_stream_mask_corr_loss True \
    TRAINER.two_stream_mask_self_loss True \
    TRAINER.two_stream_loss_mask_weight 5. \
    TRAINER.two_stream_mask_loss_threshold -1. \
    TRAINER.empty_cache_every 1
